### PR TITLE
Added sensible use case

### LINKED ISSUE #12: Create sensible use case
Excellent: The application contains interactions that could be monitored and leveraged for continuous experi-
mentation. For example, an operator can see predictions of the model-service and can flag/change
incorrect labels. Another option is to leverage user input for validation or growing the dataset

### PR DESCRIPTION
**Pull request by Guthax**

### CODE REVIEW

**Comment by Timdnb** [comment]
Sensible use case looks nice!

However it doesnt work for me yet, after clicking what I think, I get the following error:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

This should be fixed, but could also open a separate issue. And yes I also had the model-service container running.

**Comment by Timdnb** [comment]
Also the version still shows "unknown"

**Comment by SagaRut** [comment]
> Also the version still shows "unknown"

Ah yeah I have an issue for that in the lib-version repo

**Review by Timdnb — APPROVED** [review]
Since the application works (at least for me) we can also merge this

**Pull request merged**
